### ISSUE TITLE
Problem starting docker

### ISSUE THREAD

**Issue by jeffreywhunter** [shrmnk/gsdock#1]
Just installed GoodSync Connect.    Got the following when I tried to start the docker.

gs-server: Profile at /root/.goodsync/server
181020-223946 2b39e740 === Started GoodSync Server (R) Ver 10.9.10.5 OS: 0.0 build 0
GoodSync Server ver 10.9.10.5
License: Pro=0 Trial=1
sed: can't read /root/.goodsync/server/settings.tix: No such file or directory
gs-server: Profile at /root/.goodsync/server
181020-224058 c0471740 === Started GoodSync Server (R) Ver 10.9.10.5 OS: 0.0 build 0
GoodSync Server ver 10.9.10.5
License: Pro=0 Trial=1
sed: can't read /root/.goodsync/server/settings.tix: No such file or directory

Thanks in advance!

**Comment by jeffreywhunter** [comment]
Just FYI,
I have an account with Goodsync Connect. I used the account configured in the Docker.  I have verified my goodsync connect account. I'm getting "no such container" errors... Goodsync Connect is installed in a contain on UnRaid v 6.4.x.

ErrorWarningSystemArrayLogings-server: Profile at /root/.goodsync/server181020-225021 b49bb740 === Started GoodSync Server (R) Ver 10.9.10.5 OS: 0.0 build 0GoodSync Server ver 10.9.10.5License: Pro=0 Trial=1sed: can't read /root/.goodsync/server/settings.tix: No such file or directorygs-server: Profile at /root/.goodsync/server181020-225033 ca1a6740 === Started GoodSync Server (R) Ver 10.9.10.5 OS: 0.0 build 0GoodSync Server ver 10.9.10.5License: Pro=0 Trial=1sed: can't read /root/.goodsync/server/settings.tix: No such file or directorye":"No such container: 871d53de7a6e"}e":"No such container: 871d53de7a6e"}e":"No such container: 871d53de7a6e"}e":"No such container: 871d53de7a6e"}e":"No such container: 871d53de7a6e"}e":"No such container: 871d53de7a6e"}e":"No such container: 871d53de7a6e"}e":"No such container: 871d53de7a6e"}e":"No such container: 871d53de7a6e"}e":"No such container: 871d53de7a6e"}e":"No such container: 871d53de7a6e"}e":"No such container: 871d53de7a6e"}e":"No such container: 871d53de7a6e"}e":"No such container: 871d53de7a6e"}e":"No such container: 871d53de7a6e"}e":"No such container: 871d53de7a6e"}e":"No such container: 871d53de7a6e"}e":"No such container: 871d53de7a6e"}e":"No such container: 871d53de7a6e"}e":"No such container: 871d53de7a6e"}e":"No such container: 871d53de7a6e"}e":"No such container: 871d53de7a6e"}e":"No such container: 871d53de7a6e"}e":"No such container: 871d53de7a6e"}
--

**Comment by sreknob** [comment]
It looks like it can't find your settings.tix file.

What are your mappings?

Might use /root/.goodsync/server instead of /root/.goodsync

-v '/mnt/user/':'/data':'rw' -v '/mnt/user/appdata/GoodSync':'/root/.goodsync/server':'rw'

**Comment by jeffreywhunter** [comment]
Well, that changed(improved?) things.  Now when I try to start the docker, I get the following:

`Oct 21 17:31:15 HunterNAS kernel: device vetheb22c66 entered promiscuous mode
Oct 21 17:31:15 HunterNAS kernel: IPv6: ADDRCONF(NETDEV_UP): vetheb22c66: link is not ready
Oct 21 17:31:15 HunterNAS kernel: docker0: port 1(vetheb22c66) entered blocking state
Oct 21 17:31:15 HunterNAS kernel: docker0: port 1(vetheb22c66) entered forwarding state
Oct 21 17:31:15 HunterNAS kernel: docker0: port 1(vetheb22c66) entered disabled state
Oct 21 17:31:16 HunterNAS kernel: eth0: renamed from veth2d99efb
Oct 21 17:31:16 HunterNAS kernel: IPv6: ADDRCONF(NETDEV_CHANGE): vetheb22c66: link becomes ready
Oct 21 17:31:16 HunterNAS kernel: docker0: port 1(vetheb22c66) entered blocking state
Oct 21 17:31:16 HunterNAS kernel: docker0: port 1(vetheb22c66) entered forwarding state
Oct 21 17:31:16 HunterNAS kernel: docker0: port 1(vetheb22c66) entered disabled state
Oct 21 17:31:16 HunterNAS kernel: veth2d99efb: renamed from eth0
Oct 21 17:31:16 HunterNAS kernel: docker0: port 1(vetheb22c66) entered disabled state
Oct 21 17:31:16 HunterNAS kernel: device vetheb22c66 left promiscuous mode
Oct 21 17:31:16 HunterNAS kernel: docker0: port 1(vetheb22c66) entered disabled state`

Thanks!
Jeff...

**Comment by shrmnk** [comment]
Could you enter your Unraid server (ssh or otherwise) and browse to the directory you have set your configuration folder in? (probably appdata/gsdock) 

Check if the `settings.tix` file was created, and check the owner (`stat settings.tix`) if so.

**Comment by jeffreywhunter** [comment]
No worries, hope the trip goes well.

Did not find that file in any directory.  See attached screenshot...

Thanks for your help!
Jeff...

On October 23, 2018 11:43:37 AM CDT, Sherman K <notifications@github.com> wrote:
>Could you enter your Unraid server (ssh or otherwise) and browse to the
>directory you have set your configuration folder in? (probably
>appdata/gsdock) 
>
>Check if the `settings.tix` file was created, and check the owner
>(`stat settings.tix`) if so.
>
>Apologies for the delayed reply - am overseas at the moment and have
>limited connectivity

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by shrmnk** [comment]
@jeffreywhunter Give it a go, I've added some commands to the script to create an empty settings.tix file if it does not exist. GoodSync Server will then populate the file with default values after the first run. 
You should then be able to access the web UI on port 11000 and modify the values from there.

**Comment by shrmnk** [comment]
So I've pretty much re-written the whole thing to be based on linuxserver.io's ubuntu image. Should resolve all the permission issues now. I've tested it on my production server, sync speeds are faster than ever after changing network type to `host` instead of `bridge`, which enables LAN discovery instead of needing to go through the forwarder.

**Comment by jeffreywhunter** [comment]
Its been working well until I upgraded from 6.4.3 to 6.6.5 UnRaid.  Now I'm seeing this in my logs...

`Nov 29 21:25:32 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Nov 29 21:29:32 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Nov 29 21:33:32 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Nov 29 21:37:32 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Nov 29 21:41:32 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Nov 29 21:45:32 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Nov 29 21:49:33 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Nov 29 21:53:33 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Nov 29 21:57:34 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Nov 29 22:01:34 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Nov 29 22:05:34 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Nov 29 22:09:34 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Nov 29 22:13:34 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Nov 29 22:17:52 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Nov 29 22:21:52 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Nov 29 22:25:52 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Nov 29 22:29:52 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Nov 29 22:33:52 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.`

Are you seeing these?  Everything works.  All GS jobs are completing without errors.

Thanks in advance!

**Comment by shrmnk** [comment]
Are these appearing in the docker application's log or in unraid logs?

**Comment by jeffreywhunter** [comment]
The unRaid logs.  SysLog attached, sorry, I should have included that in my
original email.

 

Take care...

Jeff...

 

Jeff Hunter  |  direct  262 323-1550  |  email
jeff.hunter@accessAmericaGroup.com
<mailto:Jeff.hunter@accessamericagroup.com> 

 

accessAmerica Group, LLC

planning & execution for rational growth

 

10800 43rd Ave

Pleasant Prairie, WI 53158

 

© Copyright 2018 All rights reserved. accessAmericaGroup, LLC.™

 

Internet Email Confidentiality
Privileged/Confidential Information may be contained in this message. 
If you are not the addressee indicated in this message (or responsible for
delivery of the message to such person), you may not copy or deliver this
message to anyone. In such case, you should destroy this message and kindly
notify the sender by reply email. Please advise immediately if you or your
employer does not consent to Internet email for messages of this kind.
Opinions, conclusions and other information in this message that do not
relate to the official business of accessAmericaGroup, LLC. shall be
understood as neither given nor endorsed by it.

**Comment by shrmnk** [comment]
@jeffreywhunter the attachments aren't appearing on GitHub Issues, could you upload it on pastebin or similar?

**Comment by jeffreywhunter** [comment]
Sure!

 

https://www.dropbox.com/s/2be0hrtlsdiu9z6/hunternas-diagnostics-20181130-0612.zip?dl=0

 

Thanks!

 

Take care...

Jeff...

 

Jeff Hunter  |  direct  262 323-1550  |  email  jeff.hunter@accessAmericaGroup.com <mailto:Jeff.hunter@accessamericagroup.com> 

 

accessAmerica Group, LLC

planning & execution for rational growth

 

10800 43rd Ave

Pleasant Prairie, WI 53158

 

© Copyright 2018 All rights reserved. accessAmericaGroup, LLC.™

 

Internet Email Confidentiality
Privileged/Confidential Information may be contained in this message. 
If you are not the addressee indicated in this message (or responsible for delivery of the message to such person), you may not copy or deliver this message to anyone. In such case, you should destroy this message and kindly notify the sender by reply email. Please advise immediately if you or your employer does not consent to Internet email for messages of this kind. Opinions, conclusions and other information in this message that do not relate to the official business of accessAmericaGroup, LLC. shall be understood as neither given nor endorsed by it.
