### ISSUE TITLE
Cannot access via webUI

### ISSUE THREAD

**Issue by yusufLimz** [shrmnk/gsdock#3]
I've got a verified GoodSync account - which I can login with using the same credentials.

But I can't access the WebUI  - always says authentication failed.

Is there a password limit? maybe something to do with special characters?

**Comment by shrmnk** [comment]
Did you set the `GS_USER` and `GS_PWD` variables? Unraid should keep them quoted as environment variables.

**Comment by yusufLimz** [comment]
Yup created a GS account and used the same credentials in those variables.

**Comment by shrmnk** [comment]
I'll verify this later this week.

**Comment by shrmnk** [comment]
I have tried to reproduce this on my production server and on my home lab, but can see no issue logging in to the Web UI. 

Take note that the WebUI authenticates with GoodSync, so your credentials must be correct and current.

Could you try changing your password and logging in on https://www.goodsync.com/manage ?
