### ISSUE TITLE
Default networking mode isn't host

### ISSUE THREAD

**Issue by yusufLimz** [shrmnk/gsdock#4]
When creating the container it defaults to bridge

**Comment by shrmnk** [comment]
Bridge is the default as defined in https://github.com/shrmnk/docker-templates/blob/master/shrmn/gsdock.xml

<blockquote><img src="https://avatars2.githubusercontent.com/u/859780?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/shrmnk/docker-templates">shrmnk/docker-templates</a></strong></div><div>Docker templates for unRAID to be used with the Community Applications Plugin - shrmnk/docker-templates</div></blockquote>

**Comment by yusufLimz** [comment]
Ah okay. I saw in the Readme:

- Default networking mode is now host instead of bridge

**Comment by shrmnk** [comment]
Ah I see it now. Thanks for the spot! 

Resolved in shrmnk/docker-templates#1
