### ISSUE TITLE
4 bytes leftover entries in log

### ISSUE THREAD

**Issue by jeffreywhunter** [shrmnk/gsdock#42]
Hi!  Really enjoying your docker.  Very helpful tool.  I'm seeing entries in my log (see below).  Shows up every 4 minutes.  Any idea what it is or how to turn this off?  Config issue?  Bug?  Thanks in advance!

`Feb 9 08:02:30 HunterNAS bunker: exported 277738 files from /mnt/disk1. Duration: 00:01:27
Feb 9 08:02:40 HunterNAS bunker: exported 408250 files from /mnt/disk11. Duration: 00:01:37
Feb 9 08:05:37 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Feb 9 08:09:37 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Feb 9 08:13:37 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Feb 9 08:17:37 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Feb 9 08:21:37 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Feb 9 08:25:37 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Feb 9 08:26:29 HunterNAS kernel: mdcmd (80): spindown 3
Feb 9 08:29:37 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Feb 9 08:33:37 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Feb 9 08:37:37 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Feb 9 08:41:38 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Feb 9 08:45:38 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Feb 9 08:49:38 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Feb 9 08:52:14 HunterNAS preclear_disk_AR31021EHUX5HC[19584]: Pre-Read: progress - 60% read
Feb 9 08:53:38 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Feb 9 08:57:38 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Feb 9 09:00:02 HunterNAS crond[1700]: exit status 1 from user root /usr/local/sbin/mover &> /dev/null
Feb 9 09:01:38 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Feb 9 09:05:38 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Feb 9 09:09:38 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Feb 9 09:13:38 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Feb 9 09:17:38 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.
Feb 9 09:18:07 HunterNAS emhttpd: cmd: /usr/local/emhttp/plugins/dynamix.file.integrity/scripts/duplicates 128
Feb 9 09:18:25 HunterNAS emhttpd: cmd: /usr/local/emhttp/plugins/dynamix.file.integrity/scripts/duplicates 128 more
Feb 9 09:20:29 HunterNAS emhttpd: cmd: /usr/local/emhttp/plugins/dynamix.plugin.manager/scripts/plugin checkos
Feb 9 09:21:38 HunterNAS kernel: netlink: 4 bytes leftover after parsing attributes in process `gs-server'.`

**Comment by shrmnk** [comment]
Hey Jeff, unfortunately I am unable to reproduce the above on either of my servers and can't help you with this issue (I remember seeing these logs from you in another issue).

**Comment by jeffreywhunter** [comment]
Hey, no worries, I'll follow-up with Goodsync and see what they say.  It appears to be an error reported by other linux systems, so who know...  I'll let you know what I find out...

**Comment by jeffreywhunter** [comment]
I posted the question to Goodsync.  Here's their reply...

William replied (2020/02/10 11:32 am EST)this is a known bug in Linux, has nothing to do with GS
Mike replied (2020/02/10 11:30 am EST)Hello,The error you are receiving is related to Linux and not GoodSync.Linux - netlink: 4 bytes leftover after parsing attributes in process. You will need to address this with your device directly.Thank you. | Mike replied (2020/02/10 11:30 am EST)
