### ISSUE TITLE
IP Address?

### ISSUE THREAD

**Issue by jeffreywhunter** [shrmnk/gsdock#6]
Hey Sherman,

Just noticed that when I display the advanced dashboard, I see the following:

http://my.jetscreenshot.com/12412/20190311-zrjm-26kb.jpg

Can you tell me what the 172.x.x.x addresses are for?

Thanks!
jeff...

PS.  Your software has worked flawlessly!

**Comment by shrmnk** [comment]
Because you have set up the container in Bridge mode, the container is given an internal IP address by Docker. Those addresses are your 172.* in your screenshot.

Docker then maps the exposed ports from the internal port of the container to the external port of your host (the 192.* address).

**Comment by jeffreywhunter** [comment]
Hey Sherman,

 

Should I set it up as host instead?  Not sure if there are any performance benefits either way…

 

Take care...

Jeff...

 

Jeff Hunter  |  direct  262 323-1550  |  email  jeff.hunter@accessAmericaGroup.com <mailto:Jeff.hunter@accessamericagroup.com> 

 

accessAmericaGroup, LLC

planning & execution for rational growth

 

10800 43rd Ave

Pleasant Prairie, WI 53158

 

© Copyright 2018 All rights reserved. accessAmericaGroup, LLC.™

 

Internet Email Confidentiality
Privileged/Confidential Information may be contained in this message. 
If you are not the addressee indicated in this message (or responsible for delivery of the message to such person), you may not copy or deliver this message to anyone. In such case, you should destroy this message and kindly notify the sender by reply email. Please advise immediately if you or your employer does not consent to Internet email for messages of this kind. Opinions, conclusions and other information in this message that do not relate to the official business of accessAmericaGroup, LLC. shall be understood as neither given nor endorsed by it.

**Comment by shrmnk** [comment]
Yes, you should if you want the broadcast to work on your local network. This means computers on your network will be able to see the GS server on the GUI without you needing to key in the IP manually.

If it works fine on your current system then it should not be an issue. Performance differences should be negligible.

_By the way, when you reply via email, your email footer gets attached to the bottom including your DID and email. I've edited your reply to remove them, but just take note!_

**Comment by jeffreywhunter** [comment]
Thanks Sherman, I’ll make that change.

 

By the way, I was in my log this morning regarding a preclear that keeps
failing and I noticed the following in the log repeated dozens of times…

 

Mar 12 07:08:55 HunterNAS kernel: netlink: 4 bytes leftover after parsing
attributes in process `gs-server'.

 

Is it important? 

 

Take care...

Jeff...

 

Jeff Hunter  |  direct  262 323-1550  |  email
jeff.hunter@accessAmericaGroup.com
<mailto:Jeff.hunter@accessamericagroup.com> 

 

accessAmericaGroup, LLC

planning & execution for rational growth

 

10800 43rd Ave

Pleasant Prairie, WI 53158

 

© Copyright 2018 All rights reserved. accessAmericaGroup, LLC.™

 

Internet Email Confidentiality
Privileged/Confidential Information may be contained in this message. 
If you are not the addressee indicated in this message (or responsible for
delivery of the message to such person), you may not copy or deliver this
message to anyone. In such case, you should destroy this message and kindly
notify the sender by reply email. Please advise immediately if you or your
employer does not consent to Internet email for messages of this kind.
Opinions, conclusions and other information in this message that do not
relate to the official business of accessAmericaGroup, LLC. shall be
understood as neither given nor endorsed by it.

**Comment by shrmnk** [comment]
I don't actually have an idea as to why that would happen. I don't have that line on my logs, and the difference between yours and mine would be that the network mode is set to Host instead of Bridge.

Could you see if the line still appears after changing the network mode?

**Comment by jeffreywhunter** [comment]
Hey Sherman,

 

Interesting.  Switched from Bridge to Host and it stopped…

 

http://my.jetscreenshot.com/12412/20190312-hmvm-256kb.jpg

 

 

Take care...

Jeff...

 

Jeff Hunter  |  direct  262 323-1550  |  email  jeff.hunter@accessAmericaGroup.com <mailto:Jeff.hunter@accessamericagroup.com> 

 

accessAmericaGroup, LLC

planning & execution for rational growth

 

10800 43rd Ave

Pleasant Prairie, WI 53158

 

© Copyright 2018 All rights reserved. accessAmericaGroup, LLC.™

 

Internet Email Confidentiality
Privileged/Confidential Information may be contained in this message. 
If you are not the addressee indicated in this message (or responsible for delivery of the message to such person), you may not copy or deliver this message to anyone. In such case, you should destroy this message and kindly notify the sender by reply email. Please advise immediately if you or your employer does not consent to Internet email for messages of this kind. Opinions, conclusions and other information in this message that do not relate to the official business of accessAmericaGroup, LLC. shall be understood as neither given nor endorsed by it.

**Comment by shrmnk** [comment]
@jeffreywhunter That's good to hear! I'll add a note in the README. Thanks!
